DefaultContentLanguage = "en"
languageCode = "en"
title = "Don Alfons Nisnoni"

[params]
author = "Don Alfons Nisnoni"
twitter_username = "AlfonsDon"

[taxonomies]
tag = "tags"
lyric = "lyrics"

[build]
writeStats = true

[markup]
[markup.highlight]
noClasses = false
tabWidth = 4

[markup.goldmark.renderer]
unsafe = true
